//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkDACE.ServiceParkingSpot {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceParkingSpot.IServiceParkingSpot")]
    public interface IServiceParkingSpot {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceParkingSpot/GetSpots", ReplyAction="http://tempuri.org/IServiceParkingSpot/GetSpotsResponse")]
        BOT_SpotSensors.Spot[] GetSpots();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceParkingSpot/GetSpots", ReplyAction="http://tempuri.org/IServiceParkingSpot/GetSpotsResponse")]
        System.Threading.Tasks.Task<BOT_SpotSensors.Spot[]> GetSpotsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceParkingSpotChannel : ParkDACE.ServiceParkingSpot.IServiceParkingSpot, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceParkingSpotClient : System.ServiceModel.ClientBase<ParkDACE.ServiceParkingSpot.IServiceParkingSpot>, ParkDACE.ServiceParkingSpot.IServiceParkingSpot {
        
        public ServiceParkingSpotClient() {
        }
        
        public ServiceParkingSpotClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceParkingSpotClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceParkingSpotClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceParkingSpotClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BOT_SpotSensors.Spot[] GetSpots() {
            return base.Channel.GetSpots();
        }
        
        public System.Threading.Tasks.Task<BOT_SpotSensors.Spot[]> GetSpotsAsync() {
            return base.Channel.GetSpotsAsync();
        }
    }
}
